/**
 * Copyright (C) 2026 Peter Paul Bakker, Stokpop Software Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nl.stokpop.typemapper.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.core.requireObject
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.multiple
import com.github.ajalt.clikt.parameters.options.option
import nl.stokpop.typemapper.analyzer.KotlinTypeMapper
import nl.stokpop.typemapper.analyzer.findProjectRoot
import nl.stokpop.typemapper.analyzer.resolveProjectClasspath
import nl.stokpop.typemapper.model.TypedAstJson
import nl.stokpop.typemapper.model.calls
import nl.stokpop.typemapper.model.declarations
import java.io.File

class AnalyzeCommand : CliktCommand("analyze") {
    override fun help(context: Context) = "Analyze Kotlin sources and emit a JSON AST."

    val verbose by requireObject<Boolean>()
    val sourceDir by argument("SOURCE_DIR", help = "Root directory of Kotlin sources")
    val output    by option("--output", "-o", help = "Write JSON to FILE (default: stdout)")
    val classpath by option("--classpath", "-cp",
        help = "Extra classpath entry: jar file or class directory (repeatable; default: auto-resolved via Gradle/Maven)").multiple()
    val extraSources by option("--extra-sources", "-s",
        help = "Additional source root to include (repeatable; e.g. target/generated-sources/openapi/src/main/kotlin)").multiple()
    val includeGenerated by option("--include-generated", "-g",
        help = "Auto-detect and include generated Kotlin sources under target/generated-sources and build/generated").flag()

    override fun run() {
        val dir = File(sourceDir).absoluteFile
        require(dir.isDirectory) { "SOURCE_DIR does not exist: $sourceDir" }

        val projectRoot = findProjectRoot(dir)

        val extraClasspath: List<File> = if (classpath.isNotEmpty()) {
            if (verbose) {
                echo("Classpath (explicit): ${classpath.size} entries", err = true)
                classpath.forEach { entry -> echo("  cp: $entry", err = true) }
            }
            classpath.map { File(it) }.filter { it.isDirectory || it.extension == "jar" }
        } else {
            val root = findProjectRoot(dir)
            if (root != null) {
                echo("Resolving classpath from: $root", err = true)
                resolveProjectClasspath(root).filter { it.isDirectory || it.extension == "jar" }.also {
                    val jars = it.count { f -> f.isFile && f.extension == "jar" }
                    val dirs = it.count { f -> f.isDirectory }
                    echo("Classpath: $jars jar(s), $dirs dir(s)", err = true)
                    if (verbose) {
                        it.forEach { entry -> echo("  cp: $entry", err = true) }
                    }
                }
            } else {
                echo("No build file found; skipping dependency classpath", err = true)
                emptyList()
            }
        }

        val generatedDirs: List<File> = if (includeGenerated && projectRoot != null) {
            findGeneratedKotlinSourceDirs(projectRoot).also {
                if (it.isNotEmpty()) echo("Generated sources: ${it.size} dir(s)", err = true)
                if (verbose) it.forEach { d -> echo("  gen: $d", err = true) }
            }
        } else emptyList()

        val allSourceDirs = (listOf(dir) + extraSources.map { File(it) } + generatedDirs)
            .map { it.absoluteFile }
            .filter { it.isDirectory }
            .distinct()

        val totalKtFiles = allSourceDirs.sumOf { d ->
            d.walkTopDown().count { it.extension == "kt" }
        }
        echo("Analyzing $totalKtFiles Kotlin file(s) across ${allSourceDirs.size} source root(s)", err = true)
        if (verbose && allSourceDirs.size > 1) {
            allSourceDirs.forEach { d -> echo("  src: $d", err = true) }
        }

        val ast = KotlinTypeMapper(allSourceDirs, extraClasspath).analyze()
        val json = TypedAstJson.toJsonString(ast)

        if (output != null) {
            val out = File(output!!)
            out.parentFile?.mkdirs()
            out.writeText(json)
            echo("Written ${ast.declarations().size} declarations, ${ast.calls().size} call sites → ${out.absolutePath}", err = true)
        } else {
            echo(json)
        }
    }
}

/**
 * Finds directories under [projectRoot] that contain generated Kotlin source files.
 * Searches under `target/generated-sources` (Maven) and `build/generated` (Gradle).
 * Returns only the deepest directories that directly contain `.kt` files, to avoid
 * passing overly broad roots to the compiler.
 */
fun findGeneratedKotlinSourceDirs(projectRoot: File): List<File> {
    val generatedRoots = projectRoot.walkTopDown()
        .onEnter { dir ->
            dir.name !in setOf("src", ".git", ".gradle", "node_modules")
                && !(dir.name == "classes" && dir.parentFile?.name == "target")
                && !(dir.name == "classes" && dir.parentFile?.name == "build")
        }
        .filter { it.isDirectory && it.name == "generated-sources" && it.parentFile?.name == "target" ||
                  it.isDirectory && it.name == "generated"          && it.parentFile?.name == "build"  }
        .toList()

    return generatedRoots.flatMap { root ->
        root.walkTopDown()
            .filter { dir -> dir.isDirectory && dir.listFiles()?.any { it.extension == "kt" } == true }
            .toList()
    }.distinct()
}
